name: Extract TVG IDs

on:
  schedule:
    - cron: "0 18 * * *"  # 01:00 giờ Hà Nội (UTC+7 = 18:00 UTC)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install requests

      - name: Extract TVG IDs
        run: python scripts/extract_tvg_ids.py

      - name: Commit and push results
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add docs/tvg_ids.txt
          git commit -m "Cập nhật danh sách TVG IDs tự động" || echo "Không có thay đổi"
          git push
          
