name: Update EPG Test

on:
  workflow_dispatch:
  schedule:
    - cron: "0 19 * * *" # 2:00 AM VN = 19:00 UTC previous day (adjust if needed)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pytz python-dateutil

      - name: Run epgtest.py (TEST MODE)
        run: |
          echo "=== RUNNING epgtest.py (TEST MODE) ==="
          python epgtest.py

      - name: Commit and push results
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/epgtest.xml || true
          git commit -m "Auto update epgtest.xml [test]" || echo "No changes to commit"
          git push || echo "Push failed"
          
