name: Update EPG

on:
  schedule:
    # 18:00 UTC = 01:00 sáng giờ Hà Nội (UTC+7)
    - cron: "0 18 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install requests pytz

      - name: Run EPG generator
        run: python epg.py

      - name: Commit and push EPG
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add docs/epg.xml
          git commit -m "Auto-update EPG $(date '+%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
          git push
          
