name: Update EPG

on:
  schedule:
    - cron: '0 1 * * *'   # chạy mỗi ngày lúc 08:00 sáng giờ Việt Nam
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4 lxml python-dateutil pytz

      - name: Run EPG generator
        run: python epg.py

      - name: Commit and push changes
        uses: EndBug/add-and-commit@v9
        with:
          message: "Auto update EPG"
          add: "docs/epg.xml"
          
