name: Update EPG

on:
  schedule:
    - cron: "0 18 * * *"  # chạy lúc 01h sáng Hà Nội
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          pip install requests pytz
      - name: Run epg.py
        run: python epg.py
      - name: Commit and push
        uses: EndBug/add-and-commit@v9
        with:
          message: "Auto update EPG"
          add: "docs/epg.xml"
          
