name: Update EPG

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"  # Chạy mỗi 6 tiếng

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pytz beautifulsoup4

      - name: Run EPG script
        run: python epg.py

      - name: Commit and push changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions[bot]
          author_email: 41898282+github-actions[bot]@users.noreply.github.com
          message: "Update epg.xml"
          add: "docs/epg.xml"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
